/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as HomoglyphsRouteImport } from './routes/homoglyphs'
import { Route as IdnRouteImport } from './routes/idn'
import { Route as IdnaRouteImport } from './routes/idna'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SampleReportRouteImport } from './routes/sample-report'
import { Route as ZeroWidthRouteImport } from './routes/zero-width'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgentsRouteImport } from './routes/app/agents'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCorpusRouteImport } from './routes/app/corpus'
import { Route as AppCoursesRouteImport } from './routes/app/courses'
import { Route as AppHomoglyphsRouteImport } from './routes/app/homoglyphs'
import { Route as AppIdnRouteImport } from './routes/app/idn'
import { Route as AppIdnaRouteImport } from './routes/app/idna'
import { Route as AppLibrariesRouteImport } from './routes/app/libraries'
import { Route as AppMoodleRouteImport } from './routes/app/moodle'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppOrganisationRouteImport } from './routes/app/organisation'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppPlatformRouteImport } from './routes/app/platform'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSubmissionsRouteImport } from './routes/app/submissions'
import { Route as AppSubmitRouteImport } from './routes/app/submit'
import { Route as AppTrainingRouteImport } from './routes/app/training'
import { Route as AppZeroWidthRouteImport } from './routes/app/zero-width'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1CheckRouteImport } from './routes/api/v1/check'
import { Route as AppReportsReportIdRouteImport } from './routes/app/reports.$reportId'
import { Route as ApiV1ReportsReportIdRouteImport } from './routes/api/v1/reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HomoglyphsRoute = HomoglyphsRouteImport.update({
  id: '/homoglyphs',
  path: '/homoglyphs',
  getParentRoute: () => rootRouteImport,
} as any)
const IdnRoute = IdnRouteImport.update({
  id: '/idn',
  path: '/idn',
  getParentRoute: () => rootRouteImport,
} as any)
const IdnaRoute = IdnaRouteImport.update({
  id: '/idna',
  path: '/idna',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleReportRoute = SampleReportRouteImport.update({
  id: '/sample-report',
  path: '/sample-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroWidthRoute = ZeroWidthRouteImport.update({
  id: '/zero-width',
  path: '/zero-width',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCorpusRoute = AppCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomoglyphsRoute = AppHomoglyphsRouteImport.update({
  id: '/homoglyphs',
  path: '/homoglyphs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdnRoute = AppIdnRouteImport.update({
  id: '/idn',
  path: '/idn',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdnaRoute = AppIdnaRouteImport.update({
  id: '/idna',
  path: '/idna',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrariesRoute = AppLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMoodleRoute = AppMoodleRouteImport.update({
  id: '/moodle',
  path: '/moodle',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmitRoute = AppSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppZeroWidthRoute = AppZeroWidthRouteImport.update({
  id: '/zero-width',
  path: '/zero-width',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CheckRoute = ApiV1CheckRouteImport.update({
  id: '/api/v1/check',
  path: '/api/v1/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1ReportsReportIdRoute = ApiV1ReportsReportIdRouteImport.update({
  id: '/api/v1/reports/$reportId',
  path: '/api/v1/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/homoglyphs': typeof HomoglyphsRoute
  '/idn': typeof IdnRoute
  '/idna': typeof IdnaRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sample-report': typeof SampleReportRoute
  '/zero-width': typeof ZeroWidthRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/homoglyphs': typeof AppHomoglyphsRoute
  '/app/idn': typeof AppIdnRoute
  '/app/idna': typeof AppIdnaRoute
  '/app/libraries': typeof AppLibrariesRoute
  '/app/moodle': typeof AppMoodleRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app/zero-width': typeof AppZeroWidthRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/homoglyphs': typeof HomoglyphsRoute
  '/idn': typeof IdnRoute
  '/idna': typeof IdnaRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sample-report': typeof SampleReportRoute
  '/zero-width': typeof ZeroWidthRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/homoglyphs': typeof AppHomoglyphsRoute
  '/app/idn': typeof AppIdnRoute
  '/app/idna': typeof AppIdnaRoute
  '/app/libraries': typeof AppLibrariesRoute
  '/app/moodle': typeof AppMoodleRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app/zero-width': typeof AppZeroWidthRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/homoglyphs': typeof HomoglyphsRoute
  '/idn': typeof IdnRoute
  '/idna': typeof IdnaRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sample-report': typeof SampleReportRoute
  '/zero-width': typeof ZeroWidthRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/homoglyphs': typeof AppHomoglyphsRoute
  '/app/idn': typeof AppIdnRoute
  '/app/idna': typeof AppIdnaRoute
  '/app/libraries': typeof AppLibrariesRoute
  '/app/moodle': typeof AppMoodleRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app/zero-width': typeof AppZeroWidthRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/homoglyphs'
    | '/idn'
    | '/idna'
    | '/libraries'
    | '/login'
    | '/privacy'
    | '/sample-report'
    | '/zero-width'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audit'
    | '/app/corpus'
    | '/app/courses'
    | '/app/homoglyphs'
    | '/app/idn'
    | '/app/idna'
    | '/app/libraries'
    | '/app/moodle'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app/zero-width'
    | '/app/'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/homoglyphs'
    | '/idn'
    | '/idna'
    | '/libraries'
    | '/login'
    | '/privacy'
    | '/sample-report'
    | '/zero-width'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audit'
    | '/app/corpus'
    | '/app/courses'
    | '/app/homoglyphs'
    | '/app/idn'
    | '/app/idna'
    | '/app/libraries'
    | '/app/moodle'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app/zero-width'
    | '/app'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/homoglyphs'
    | '/idn'
    | '/idna'
    | '/libraries'
    | '/login'
    | '/privacy'
    | '/sample-report'
    | '/zero-width'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audit'
    | '/app/corpus'
    | '/app/courses'
    | '/app/homoglyphs'
    | '/app/idn'
    | '/app/idna'
    | '/app/libraries'
    | '/app/moodle'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app/zero-width'
    | '/app/'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HomoglyphsRoute: typeof HomoglyphsRoute
  IdnRoute: typeof IdnRoute
  IdnaRoute: typeof IdnaRoute
  LibrariesRoute: typeof LibrariesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SampleReportRoute: typeof SampleReportRoute
  ZeroWidthRoute: typeof ZeroWidthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1CheckRoute: typeof ApiV1CheckRoute
  ApiV1ReportsReportIdRoute: typeof ApiV1ReportsReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homoglyphs': {
      id: '/homoglyphs'
      path: '/homoglyphs'
      fullPath: '/homoglyphs'
      preLoaderRoute: typeof HomoglyphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idn': {
      id: '/idn'
      path: '/idn'
      fullPath: '/idn'
      preLoaderRoute: typeof IdnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idna': {
      id: '/idna'
      path: '/idna'
      fullPath: '/idna'
      preLoaderRoute: typeof IdnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-report': {
      id: '/sample-report'
      path: '/sample-report'
      fullPath: '/sample-report'
      preLoaderRoute: typeof SampleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-width': {
      id: '/zero-width'
      path: '/zero-width'
      fullPath: '/zero-width'
      preLoaderRoute: typeof ZeroWidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/corpus': {
      id: '/app/corpus'
      path: '/corpus'
      fullPath: '/app/corpus'
      preLoaderRoute: typeof AppCorpusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/homoglyphs': {
      id: '/app/homoglyphs'
      path: '/homoglyphs'
      fullPath: '/app/homoglyphs'
      preLoaderRoute: typeof AppHomoglyphsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/idn': {
      id: '/app/idn'
      path: '/idn'
      fullPath: '/app/idn'
      preLoaderRoute: typeof AppIdnRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/idna': {
      id: '/app/idna'
      path: '/idna'
      fullPath: '/app/idna'
      preLoaderRoute: typeof AppIdnaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/libraries': {
      id: '/app/libraries'
      path: '/libraries'
      fullPath: '/app/libraries'
      preLoaderRoute: typeof AppLibrariesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/moodle': {
      id: '/app/moodle'
      path: '/moodle'
      fullPath: '/app/moodle'
      preLoaderRoute: typeof AppMoodleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organisation': {
      id: '/app/organisation'
      path: '/organisation'
      fullPath: '/app/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/platform': {
      id: '/app/platform'
      path: '/platform'
      fullPath: '/app/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submit': {
      id: '/app/submit'
      path: '/submit'
      fullPath: '/app/submit'
      preLoaderRoute: typeof AppSubmitRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/zero-width': {
      id: '/app/zero-width'
      path: '/zero-width'
      fullPath: '/app/zero-width'
      preLoaderRoute: typeof AppZeroWidthRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/check': {
      id: '/api/v1/check'
      path: '/api/v1/check'
      fullPath: '/api/v1/check'
      preLoaderRoute: typeof ApiV1CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports/$reportId': {
      id: '/app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/reports/$reportId': {
      id: '/api/v1/reports/$reportId'
      path: '/api/v1/reports/$reportId'
      fullPath: '/api/v1/reports/$reportId'
      preLoaderRoute: typeof ApiV1ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCorpusRoute: typeof AppCorpusRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppHomoglyphsRoute: typeof AppHomoglyphsRoute
  AppIdnRoute: typeof AppIdnRoute
  AppIdnaRoute: typeof AppIdnaRoute
  AppLibrariesRoute: typeof AppLibrariesRoute
  AppMoodleRoute: typeof AppMoodleRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppSubmitRoute: typeof AppSubmitRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppZeroWidthRoute: typeof AppZeroWidthRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCorpusRoute: AppCorpusRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppHomoglyphsRoute: AppHomoglyphsRoute,
  AppIdnRoute: AppIdnRoute,
  AppIdnaRoute: AppIdnaRoute,
  AppLibrariesRoute: AppLibrariesRoute,
  AppMoodleRoute: AppMoodleRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppSubmitRoute: AppSubmitRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppZeroWidthRoute: AppZeroWidthRoute,
  AppIndexRoute: AppIndexRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  HomoglyphsRoute: HomoglyphsRoute,
  IdnRoute: IdnRoute,
  IdnaRoute: IdnaRoute,
  LibrariesRoute: LibrariesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SampleReportRoute: SampleReportRoute,
  ZeroWidthRoute: ZeroWidthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1CheckRoute: ApiV1CheckRoute,
  ApiV1ReportsReportIdRoute: ApiV1ReportsReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
