/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppCorpusRouteImport } from './routes/app/corpus'
import { Route as AppCoursesRouteImport } from './routes/app/courses'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppOrganisationRouteImport } from './routes/app/organisation'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppPlatformRouteImport } from './routes/app/platform'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSubmissionsRouteImport } from './routes/app/submissions'
import { Route as AppSubmitRouteImport } from './routes/app/submit'
import { Route as AppTrainingRouteImport } from './routes/app/training'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPayfastNotifyRouteImport } from './routes/api/payfast/notify'
import { Route as ApiV1CheckRouteImport } from './routes/api/v1/check'
import { Route as AppReportsReportIdRouteImport } from './routes/app/reports.$reportId'
import { Route as ApiV1ReportsReportIdRouteImport } from './routes/api/v1/reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCorpusRoute = AppCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmitRoute = AppSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayfastNotifyRoute = ApiPayfastNotifyRouteImport.update({
  id: '/api/payfast/notify',
  path: '/api/payfast/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CheckRoute = ApiV1CheckRouteImport.update({
  id: '/api/v1/check',
  path: '/api/v1/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1ReportsReportIdRoute = ApiV1ReportsReportIdRouteImport.update({
  id: '/api/v1/reports/$reportId',
  path: '/api/v1/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/corpus': typeof AppCorpusRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/submit': typeof AppSubmitRoute
  '/app/training': typeof AppTrainingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/corpus'
    | '/app/courses'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app/'
    | '/api/auth/$'
    | '/api/payfast/notify'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/corpus'
    | '/app/courses'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app'
    | '/api/auth/$'
    | '/api/payfast/notify'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/corpus'
    | '/app/courses'
    | '/app/onboarding'
    | '/app/organisation'
    | '/app/people'
    | '/app/platform'
    | '/app/settings'
    | '/app/submissions'
    | '/app/submit'
    | '/app/training'
    | '/app/'
    | '/api/auth/$'
    | '/api/payfast/notify'
    | '/api/v1/check'
    | '/app/reports/$reportId'
    | '/api/v1/reports/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPayfastNotifyRoute: typeof ApiPayfastNotifyRoute
  ApiV1CheckRoute: typeof ApiV1CheckRoute
  ApiV1ReportsReportIdRoute: typeof ApiV1ReportsReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/corpus': {
      id: '/app/corpus'
      path: '/corpus'
      fullPath: '/app/corpus'
      preLoaderRoute: typeof AppCorpusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organisation': {
      id: '/app/organisation'
      path: '/organisation'
      fullPath: '/app/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/platform': {
      id: '/app/platform'
      path: '/platform'
      fullPath: '/app/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submit': {
      id: '/app/submit'
      path: '/submit'
      fullPath: '/app/submit'
      preLoaderRoute: typeof AppSubmitRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payfast/notify': {
      id: '/api/payfast/notify'
      path: '/api/payfast/notify'
      fullPath: '/api/payfast/notify'
      preLoaderRoute: typeof ApiPayfastNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/check': {
      id: '/api/v1/check'
      path: '/api/v1/check'
      fullPath: '/api/v1/check'
      preLoaderRoute: typeof ApiV1CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports/$reportId': {
      id: '/app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/reports/$reportId': {
      id: '/api/v1/reports/$reportId'
      path: '/api/v1/reports/$reportId'
      fullPath: '/api/v1/reports/$reportId'
      preLoaderRoute: typeof ApiV1ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCorpusRoute: typeof AppCorpusRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppSubmitRoute: typeof AppSubmitRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppCorpusRoute: AppCorpusRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppSubmitRoute: AppSubmitRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppIndexRoute: AppIndexRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPayfastNotifyRoute: ApiPayfastNotifyRoute,
  ApiV1CheckRoute: ApiV1CheckRoute,
  ApiV1ReportsReportIdRoute: ApiV1ReportsReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
